installation:
    namespace: aigc-gateway
image:
    repository: harbor.zulong.com/common-images/aigc-gateway
    tag: "1.2"
    pullPolicy: "Always"
appId: "30ouxfu2adarnexx6bi9i"
appSecret: "2z11hf98jna6fx96flmb4"
m2mId: "8c8phprzjd7uy5u6gvdzh"
m2mSecret: "e80189syaqf6j9fkw2sqw"
host: "dashboard.aigc-gateway.zulong.com"
endpoint: "https://logto-dev.zulong.com/"
secretName: "zfleet-secret"
redis:
    address: "redis-master.aigc-gateway.svc.cluster.local:6379"
antiIdle:
    limit: "10m"
hostAliases:
  - ip: 10.236.254.133
    hostnames:
      - logto-dev.zulong.com
      - dashboard.aigc-gateway.zulong.com
